### ISSUE TITLE
Administration Screens - Capability/Permission Sets

### ISSUE THREAD

**Issue by mdfrederick** [Masterworks/Clarity-Components#10]
[Capability Sets/Permission Sets (Invision)](https://projects.invisionapp.com/share/UJJCGK5E6NX#/screens/303397030)

**Comment by Chitradip-Capitalnumbers** [comment]
@danielgolden I have done the page, please check and let me know your view.

**Comment by danielgolden** [comment]
Thanks, @Chitradip-Capitalnumbers Chitradeep. This page looks very well done. I've left a few minor points of feedback below:
- Each of these ![image](https://user-images.githubusercontent.com/812989/42589736-02ce8e8a-8510-11e8-9575-59a1b64c2903.png) should have a dotted underline rather than a solid line. Figma has a hard time rendering these 1px dotted lines so I can understand the mistake.
- The check-boxes are still too small (this is a probably an issue that needs to be resolved across all pages containing check-boxes). They should be about 18px x 18px.
- The spacing between the "Edit Permission Sets" header and the top of the `.o-shadowbox` is too large
- The spacing between the "Permission Sets" select element and the paragraph above it is too small.

**Comment by Chitradip-Capitalnumbers** [comment]
@danielgolden I have done the above points, please check and let me know your view.

**Comment by mdfrederick** [comment]
@danielgolden Closing this one. Reopen if you feel there is further work that needs done.

**Comment by danielgolden** [comment]
@Chitradip-Capitalnumbers Yes, this is good to go. Thank you.
