### ISSUE TITLE
Administration Screens - Users

### ISSUE THREAD

**Issue by mdfrederick** [Masterworks/Clarity-Components#6]
[Users (Invision)](https://projects.invisionapp.com/share/UJJCGK5E6NX#/screens/302709348)

**Comment by danielgolden** [comment]
@Chitradip-Capitalnumbers I've included feedback below of some issues in the styling of the list users page. There are many _significant_ issues in the styling of this page. Please, on every page that you work on, use the specifications and measurements provided in Figma. There is no need to guess at spacing, color, width, font, etc. as the exact specifications are available in Figma.


#### Settings Button Dropdown
- [ ] The text in .dropdown-content li is vertically off-center.
- [ ] When an `<li>` in the sub-nav section (.level-2-dropdown) of dropdown-content is hovered over there’s a 1 pixel shift happening that shouldn’t.
- [ ] The label in the input of the "Apply Select codes template" list-item is set in all caps even when it's input doesn't have focus
     - [ ] There is a bug where when you focus this input it shifts the contents of the sub-nav bar to the right.

#### Secondary Navigation Bar
- [ ] The separator between the settings button and the filters is not the right color
- [ ] The spacing between each of the filter inputs is incorrect as well as the spacing between the word "filters:" and the first filter input
- [ ] The "add new user" button is missing the "active" state animation

#### Body
- [ ] The page sub-header "Settings and preferences" should be set in Proxima Nova as in figma
- [ ] The width of the two columns in the body (as well as the spacing between them is incorrect).
- [ ] Neither of the shadows for the two column backgrounds is consistent with what is in figma.
- [ ] The border-color of the aside navigation is incorrect
- [ ] The color and size of the links in the aside navigation is incorrect.
- [ ] The hover state for the aside navigation links is incorrect
- [ ] The color of the intro paragraph is incorrect.
- [ ] The pagination buttons are missing their shadow.

##### Table
- [ ] The table headers should be set in bold
- [ ] In figma the first column's text is set in the primary brand color because they are links. When that color is used on text it is because the text should be a link.
- [ ] The text in columns 3, 4, and 5 is the wrong color
- [ ] The click/tap target on on the table row menu buttons (the 3 vertical dots) needs to be larger than it currently is, these are easy to miss-click right now.

**Comment by Chitradip-Capitalnumbers** [comment]
@danielgolden  I have marked checked which are done, please check and let me know your view.

**Comment by danielgolden** [comment]
@Chitradip-Capitalnumbers I have reviewed your work on the tasks above. Thank you for the tasks that you've addressed. Several of the tasks that you've checked as completed are still incomplete, so I've gone through and unchecked the tasks that are still incomplete. For the sake of clarity I've included those still incomplete tasks below:

- Add new user button is still missing the :active state animation.
- The hover state for the aside navigation links is incorrect: 
     - There should not be any border color change. 
     - The left green bar on the left should be an indicator of which page the user is currently on (View/Edit Users, Edit Roles, etc.). It's unrelated to hover state. _There is not a hover state for this element_, and I should have specified that earlier.
- The table column headers are still not set in bold (specifically, it should be semi-bold. `font-weight: 600`). 
- The first column text are still not links.
- The text in the last 3 columns is still the wrong color.
- The click/tap target on on the table row menu buttons (the 3 vertical dots) is still too small.

### New Issues that didn't exist yesterday: 
- There's too much space between the page title and the subnav bar.
- The filters are completely missing now.

**Comment by Chitradip-Capitalnumbers** [comment]
@danielgolden  Hope you are doing good. I have done the below points yesterday but forget to push the code to git, apologize for the mistake. Please check the below points once.

- The table column headers are still not set in bold (specifically, it should be semi-bold. font-weight: 600). (Done)
- The first column text are still not links. (Done)
- The text in the last 3 columns is still the wrong color. (Done)
- The click/tap target on on the table row menu buttons (the 3 vertical dots) is still too small. (Done)

**Comment by Chitradip-Capitalnumbers** [comment]
@danielgolden  I have also made others points done, please check once which are marked as done and let me know your view.

**Comment by danielgolden** [comment]
@Chitradip-Capitalnumbers 

### Issues which still remain
- [ ] Neither the :hover nor the :active states for the primary button (add new user) are correct.
- [ ] The page subtitle should not be bold, but regular weight.
- [ ] The click/tap target of the menu buttons in each table row is still too small

### Other outstanding Issues
- [ ] The dropdown arrow in the filter should be the same color as the filter icon.
- [ ] The pagination buttons should have the same :hover and :active states as the button from the ui guide/master template.

**Comment by Chitradip-Capitalnumbers** [comment]
@danielgolden  I have done the above and marked them as checked, please check and let me know your view.

**Comment by danielgolden** [comment]
- [ ] Thank you for removing the bootstrap grid system, however still need a grid system, we just don't want to use bootstrap's (too much bloat). My preference is that you build a custom grid system for this site according to the specs in figma (16, 50px columns, with 20px gutters). This grid system should be built using css grid with a fallback for IE 10 and 11.
- [ ] Select element labels are positioned to the right and should be set in all caps.
- [ ] checkboxes are too small
- [ ] [Popover style dropdowns](https://d.pr/free/i/GeSe0B) should be placed on top of their buttons and have the same hover styles as the settings button popover drop down.

I'm glad to talk through this if you have any questions.

**Comment by Chitradip-Capitalnumbers** [comment]
@danielgolden , please check the below points and let me know your view.
1.  I have created custom grid section for the project, please check ui guide / master template. 
2. Select element labels are positioned to the right and should be set in all caps.
3.   checkboxes are too small (Done)
4.   Popover style dropdown should be placed on top of their buttons and have the same hover styles as the settings button popover drop down. (Done)

**Comment by Chitradip-Capitalnumbers** [comment]
@danielgolden I think the above issue is already resolved, please check and let me know your view.

**Comment by danielgolden** [comment]
No, this hasn't been resolve already. The problem does not seem to have been touched at all. Here is a screenshot of the issue:

![captura de pantalla 2018-07-18 a la s 6 25 08 a m copy](https://user-images.githubusercontent.com/812989/42876386-855a3266-8a54-11e8-964e-39f05f97c3fa.png)

---
Also, as far as the sizes of the checkboxes go, I wanted the exact measurements from figma, but it looks like this isn't doable without using a custom svg, and I don't want to use custom svgs just the native checkbox. So the previous size, which I believe is the largest we can get without resorting to custom images will be sufficient.

**Comment by Chitradip-Capitalnumbers** [comment]
@danielgolden and @mdfrederick 
I think the design has been updated now. So hopefully this issue has been resolved.

Thanks!

**Comment by Chitradip-Capitalnumbers** [comment]
@danielgolden 
I have updated the border thickness.

**Comment by danielgolden** [comment]
The border is good to go. Thanks, Chitradeep. There's something wrong with the standard size select text though. It's set in all caps for some reason:

<img width="783" alt="captura de pantalla 2018-07-31 a la s 8 25 44 a m" src="https://user-images.githubusercontent.com/812989/43459420-6dd9f896-949b-11e8-8a2a-7770dfce7c9f.png">

**Comment by Chitradip-Capitalnumbers** [comment]
@danielgolden

This is due to yesterdays update. I have fixed that right now.
Please check let me know your response.

Thanks!

**Comment by danielgolden** [comment]
They now have letter-spacing, but they shouldn't have any.

**Comment by danielgolden** [comment]
Good to go now.
